services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql  
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=taxi_db
    command: npx nodemon --watch src --ext ts,json --exec npx ts-node src/index.ts
    networks:
      - backend_network    

  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - '80:80'
    stdin_open: true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taxi_db
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend_network    

networks:
  backend_network:
    driver: bridge      
